POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
DELETE  http://localhost:5000/logout

###
GET http://localhost:5000/discussion/087675b6-2107-46aa-a353-af20887165e4

###
GET http://localhost:5000/discussion

###
GET http://localhost:5000/users
###
POST http://localhost:5000/discusion
Content-Type: application/json

{
    "title": "dpr",
    "content": "gmna sih anggota dpr"
}

###
DELETE  http://localhost:5000/discussion/62e20743-8925-4d6f-b144-a1d10953b196

###
GET http://localhost:5000/message

###
GET http://localhost:5000/message/3b04b049-f56d-429f-9dc1-d7f1b734a9f5


###
GET http://localhost:5000/discussionmessage/087675b6-2107-46aa-a353-af20887165e4

###
POST http://localhost:5000/message/087675b6-2107-46aa-a353-af20887165e4
Content-Type: application/json

{
    "pesan": "hamma deng"
}

###
DELETE http://localhost:5000/message/168747e8-2103-4e89-b220-b13c18bea07b

# bagian form
###
GET http://localhost:5000/form

###
POST http://localhost:5000/form
Content-Type: application/json

{
    "full_name": "Istaqom",
    "email": "IIstaqom@gmail.com",
    "phonenumber": "081256810745",
    "day": "senin",
    "hours": "10:00 - 11:00",
    "problem": "sangat ketergantungan dengan judi",
    "clientid": 3,
    "lawyerid": 6

}

###
GET http://localhost:5000/form/cc3d98eb-d3dc-4f79-8039-b0e040070451
